server:
    port: 8089

logging:
    level:
        org.springframework: DEBUG
        org.springframework.web: DEBUG
# properties
#spring:datasource.url=jdbc:mysql://localhost:3306/carrotaction?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring:
#    mvc:
#        view:
#            prefix: /WEB-INF/views
#            suffix: ".jsp"
    datasource:
        url: "jdbc:mysql://localhost:3306/carrotaction?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
        username: root
        password: 1991Qqpw@@
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        property-naming-strategy: SNAKE_CASE
